Module2 task1
htmlacademy-adaptive/2428785-cat-energy-1 pull request #2
Opened 2024-03-19 10:39 UTC by posplawone

2024-03-19 11:04 UTC, DoberBober commented on index.html
> +<!DOCTYPE html>
Логотипы в svg пересохранить.

2024-03-19 11:05 UTC, DoberBober commented on index.html
> +      <img class="logo-image" src="images/logo.png" width="202" height="59"
```suggestion
      <img class="logo__image" src="images/logo.png" width="202" height="59"
```

2024-03-19 11:06 UTC, DoberBober commented on index.html
> +          </button>
```suggestion
          <a class="program__toggle" href="#">
            Подобрать программу
          </a>
```

2024-03-19 11:07 UTC, DoberBober commented on index.html
> +          </li>
```suggestion
          <li class="work__item work__item--sheet">
            <p class="work__description">
              Функциональное питание содержит только полезные питательные вещества.
            </p>
          </li>
          <li class="work__item work__item--powder">
            <p class="work__description">
              Выпускается в виде порошка, который нужно лишь залить кипятком и готово.
            </p>
          </li>
          <li class="work__item work__item--reception">
            <p class="work__description">
              Замените один-два приема обычной еды на наше функциональное питание.
            </p>
          </li>
          <li class="work__item work__item--time">
            <p class="work__description">
              Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!
            </p>
          </li>
```

2024-03-19 11:08 UTC, DoberBober commented on index.html
> +          <span class="example__result example__result--description">снижение веса</span>
Почти всегда, когда вкладываешь два блока/элемента с одинаковыми названиями друг в друга - это что плохое.

```suggestion
        <div class="example__result">
          <p class="example__result-title">5 кг</p>
          <span class="example__result-description">снижение веса</span>
```

2024-03-19 11:09 UTC, DoberBober commented on index.html
> +        </div>
```suggestion
        <div class="example__result">
          <p class="example__result-title">60 дней</p>
          <span class="example__result-description">затрачено времени</span>
        </div>
        <div class="example__costs">
          <p class="example__cost example__cost--food">
            Затраты на питание:
          </p>
          <p class="example__cost example__cost--price">
            15 000 руб.
          </p>
        </div>
```

2024-03-19 11:09 UTC, DoberBober commented on index.html
> +    </section>
Блок с картой потерял.

2024-03-19 11:10 UTC, DoberBober commented on index.html
> +          <img class="copyright__image" src="images/html-academy.png" width="168" height="37">
```suggestion
          <img class="copyright__image" src="images/html-academy.svg" width="168" height="37">
```

2024-03-19 11:11 UTC, DoberBober commented on index.html
> +</html>
Сам файл переместить в папку `source`. И разметку остальных страниц ещё сделать.

2024-03-19 11:11 UTC, DoberBober requested changes
По БЭМу хорошо прям. Есть чуть правки, но это ерунда.

2024-03-23 08:26 UTC, DoberBober commented on source/index.html
> +      <img class="logo-image" src="img/logo.svg" width="202" height="59"
```suggestion
      <img class="logo__image" src="img/logo.svg" width="202" height="59"
```

2024-03-23 08:28 UTC, DoberBober commented on source/catalog.html
> +            <a class="products__link" href="#">
По-хорошему, вынести в блок и отнаследовать внутреннее.
```suggestion
          <li class="products__item product">
            <a class="product__link" href="#">
```

2024-03-23 08:28 UTC, DoberBober commented on source/catalog.html
> +            <p class="products__description--show">
```suggestion
            <p class="products__description-show">
```

2024-03-23 08:30 UTC, DoberBober commented on source/catalog.html
> +                  </h3>
Тут как-то запуталось всё.
Список дополнительных товаров. Каждый товар - лишка. Внутри лишки списка нет (список для равнозначных элементов только).

2024-03-23 08:30 UTC, DoberBober commented on source/catalog.html
> +                  </a>
Используешь модификаторы без основного класса.
Если есть класс `aaa__bbb--xxx`, то на этом же теге должен быть и `aaa__bbb`.

2024-03-23 08:31 UTC, DoberBober commented on source/form.html
> +          <ul class="form__list--profile">
Модификатор без основного класс. Ниже у аналогичных блоков так же.
```suggestion
          <ul class="form__list form__list--profile">
```

2024-03-23 08:32 UTC, DoberBober commented on source/form.html
> +            </li>
По-хорошему, каждую связку вынести в блок.

```suggestion
            <li class="form__item input-block">
              <label class="input-block__label" for="form__phone">Имя:*</label>
              <input class="input-block__field" id="form__phone" name="form__phone" placeholder="Барсик">
            </li>
```

2024-03-23 08:33 UTC, DoberBober commented on source/form.html
> +              </li>
```suggestion
              <li class="food__item radio-block">
                <label class="radio-block__control">
                <input class="radio-block__input visually-hidden" type="radio" name="food__program" value="slimming">
                <span class="radio-block__label">Похудение</span>
              </label>
              </li>
```

2024-03-23 08:33 UTC, DoberBober commented on source/form.html
> +        </p>
Сделай списком, чтобы структура одинаковая была. Проще будет в будущем.
Плюс тут и далее тоже связки вынести в блоки.

2024-03-23 08:34 UTC, DoberBober commented on source/form.html
> +    <section class="form">
Закрывающий тег не забудь поменять тоже.
```suggestion
    <form class="form" action="https://echo.htmlacademy.ru>
```

2024-03-23 08:34 UTC, DoberBober requested changes
В целом - хорошо. Но есть небольшие правки, которые надо внести.

2024-03-25 07:32 UTC, posplawone commented on source/catalog.html
> +            <a class="products__link" href="#">
Надеюсь правильно понял

2024-03-25 08:06 UTC, posplawone commented on source/catalog.html
> +                  </h3>
Надеюсь тоже правильно понял)

2024-03-25 08:07 UTC, posplawone commented on source/catalog.html
> +                  </a>
Вроде бы исправил

2024-03-25 08:53 UTC, DoberBober requested changes
БЭМ проверка: https://yoksel.github.io/html-tree/

form
36 +action.
57-58 food -> form.
84-95 -> email -> contacts.
99 __.
107 __.
108 additionally__list.
109 additionally__item checkbox-block.
110-112 checkbox-block__XXX.

2024-03-25 15:40 UTC, merged